name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-event-listener:
    runs-on: ubuntu-24.04
    name: Build event listener
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: |
          cd spi/event-listener
          mvn -B verify

  build-keycloak:
    runs-on: ubuntu-24.04
    name: Build Keycloak
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build .

  build-bootstrap:
    runs-on: ubuntu-24.04
    name: Build bootstrap
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          cd database
          docker build .

  test-infra:
    runs-on: ubuntu-24.04
    name: Test infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: |
          cd infra
          mvn -B verify

  build-infra:
    runs-on: ubuntu-24.04
    name: Build infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package application
        run: |
          cd infra
          mvn clean package

      - name: Synth CloudFormation templates
        env:
          PLATFORM_NAME: example
          PLATFORM_URL: https://www.example.com
          BOOTSTRAP_IMAGE: example/bootstrap:latest
          KEYCLOAK_IMAGE: example/keycloak:latest
          KEYCLOAK_DB_USER: dummy
          KEYCLOAK_ADMIN_USER: dummy
          KEYCLOAK_ADMIN_PASSWORD: dummy
          BSN_USERS_API_ENDPOINT: bsn/api/v1/users
        run: |
          cd infra
          java -jar target/infra-1.0-SNAPSHOT.jar
